import os
import sys
from pathlib import Path
#TODO: Remove this when running as a module
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# pyrefly: ignore [missing-import]
from Model.agent_models import BlogAgentState, Plan, GlobalImagePlan
# pyrefly: ignore [missing-import]
from langgraph.graph import StateGraph, END, START
from utils.agent_prompts import DECIDE_IMAGES_PROMPT
from typing import Dict, Any
from google import genai
from google.genai import types
from langchain_core.messages import SystemMessage, HumanMessage
from config.logging import get_logger

logger = get_logger("sub_graph")

# ============================================================
# ReducerWithImages Subgraph
#    merge_content -> decide_images -> generate_and_place_images
# ============================================================

async def merge_content(state: BlogAgentState) -> dict:
    """Merge all sections into a single markdown document."""
    try:
        logger.info("Merge content node started")
        plan_data = state["plan"]
        plan = Plan(**plan_data) if isinstance(plan_data, dict) else plan_data

        logger.info(f"Number of sections to merge: {len(state['sections'])}")
        for task_id, section_md in state["sections"]:
            logger.info(f"  Section {task_id}: {len(section_md)} characters")
            if len(section_md) < 50:
                logger.warning(f"  Section {task_id} is very short: {section_md[:100]}")

        ordered_sections = [md for _, md in sorted(state["sections"], key=lambda x: x[0])]
        body = "\n\n".join(ordered_sections).strip()
        merged_md = f"# {plan.blog_title}\n\n{body}\n"

        logger.info(f"Merged {len(ordered_sections)} sections, total characters: {len(merged_md)}")
        logger.debug(f"Merged markdown preview: {merged_md[:200]}...")

        return {"merged_md": merged_md, "error": None}
    except Exception as e:
        logger.log_error_with_context(e, "Error in merge_content")
        # Return fallback markdown on error
        fallback_md = "# Error\n\nFailed to merge content sections."
        return {"merged_md": fallback_md, "error": str(e)}


async def decide_images(state: BlogAgentState, llm) -> dict:
    """Decide if images are needed and generate image plan."""
    try:
        logger.info("Decide images node started")
        from langchain_groq import ChatGroq

        planner = llm.with_structured_output(GlobalImagePlan)
        merged_md = state["merged_md"]
        plan_data = state["plan"]
        plan = Plan(**plan_data) if isinstance(plan_data, dict) else plan_data

        assert plan is not None

        image_plan = await planner.ainvoke(
            [
                SystemMessage(content=DECIDE_IMAGES_PROMPT),
                HumanMessage(
                    content=(
                        f"Blog kind: {plan.blog_kind}\n"
                        f"Topic: {state.get('topic', '')}\n\n"
                        "Insert placeholders + propose image prompts.\n\n"
                        f"{merged_md}"
                    )
                ),
            ]
        )

        logger.info(f"Image plan generated with {len(image_plan.images)} images")

        return {
            "md_with_placeholders": image_plan.md_with_placeholders,
            "image_specs": [img.model_dump() for img in image_plan.images],
            "error": None
        }
    except Exception as e:
        logger.log_error_with_context(e, "Error in decide_images")
        # Fallback: use merged markdown without images
        logger.warning("Falling back to merged markdown without images")
        return {
            "md_with_placeholders": state.get("merged_md", ""),
            "image_specs": [],
            "error": str(e)
        }


async def _gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini.
    Requires: pip install google-genai
    Env var: GEMINI_API_KEY
    Returns None if quota is exhausted or generation fails.
    """
    try:
        logger.info(f"Generating image with Gemini for prompt: {prompt[:100]}...")
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            logger.error("GEMINI_API_KEY is not set")
            return None

        client = genai.Client(api_key=api_key)

        resp = client.models.generate_content(
            model="gemini-2.5-flash-image",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                safety_settings=[
                    types.SafetySetting(
                        category="HARM_CATEGORY_DANGEROUS_CONTENT",
                        threshold="BLOCK_ONLY_HIGH",
                    )
                ],
            ),
        )

        # Depending on SDK version, parts may hang off resp.candidates[0].content.parts
        parts = getattr(resp, "parts", None)
        if not parts and getattr(resp, "candidates", None):
            try:
                parts = resp.candidates[0].content.parts
            except Exception:
                parts = None

        if not parts:
            logger.error("No image content returned (safety/quota/SDK change)")
            return None

        for part in parts:
            inline = getattr(part, "inline_data", None)
            if inline and getattr(inline, "data", None):
                logger.info("Image generated successfully")
                return inline.data

        logger.error("No inline image bytes found in response")
        return None
    except Exception as e:
        error_str = str(e)
        # Check for quota exhaustion (429 error)
        if "429" in error_str or "RESOURCE_EXHAUSTED" in error_str or "quota" in error_str.lower():
            logger.warning("Gemini API quota exhausted, skipping image generation")
            return None
        logger.log_error_with_context(e, "Error generating image")
        return None


async def generate_and_place_images(state: BlogAgentState) -> dict:
    """Generate images and place them in the markdown."""
    try:
        logger.info("Generate and place images node started")
        plan_data = state["plan"]
        plan = Plan(**plan_data) if isinstance(plan_data, dict) else plan_data

        assert plan is not None

        md = state.get("md_with_placeholders") or state["merged_md"]
        image_specs = state.get("image_specs", []) or []

        # If no images requested, just use merged markdown
        if not image_specs:
            logger.info("No images requested, returning merged markdown")
            return {"markdown_content": md, "error": None}

        logger.info(f"Processing {len(image_specs)} image specifications")
        images_dir = Path("images")
        images_dir.mkdir(exist_ok=True)

        for spec in image_specs:
            placeholder = spec["placeholder"]
            filename = spec["filename"]
            out_path = images_dir / filename

            # generate only if needed
            if not out_path.exists():
                logger.info(f"Generating image: {filename}")
                img_bytes = await _gemini_generate_image_bytes(spec["prompt"])
                if img_bytes is None:
                    # Skip image generation (quota exhausted or failed), remove placeholder
                    logger.warning(f"Skipping image generation for {filename}, removing placeholder")
                    md = md.replace(placeholder, "")
                    continue
                out_path.write_bytes(img_bytes)
                logger.info(f"Image saved: {filename}")

            img_md = f"![{spec['alt']}](images/{filename})\n*{spec['caption']}*"
            md = md.replace(placeholder, img_md)

        # create a marked down file and save it
        try:
            with open("blog.md", "w", encoding="utf-8") as f:
                f.write(md)
            logger.info("Blog markdown saved to blog.md")
        except Exception as e:
            logger.log_error_with_context(e, "Error saving blog.md")
            # Continue even if file save fails

        return {"markdown_content": md, "error": None}
    except Exception as e:
        logger.log_error_with_context(e, "Error in generate_and_place_images")
        # Fallback: return merged markdown without images
        logger.warning("Falling back to merged markdown without images")
        fallback_md = state.get("merged_md", "# Error\n\nFailed to generate blog with images.")
        return {"markdown_content": fallback_md, "error": str(e)}


def create_reducer_subgraph(llm):
    """
    Create and return the reducer subgraph.
    This subgraph replaces the simple reducer function in blog_agent.py.
    
    Args:
        llm: The language model instance to use for image decision making
    
    Returns:
        Compiled subgraph that can be used as a node in the main graph
    """
    
    # Create a wrapper for decide_images that includes llm
    async def decide_images_with_llm(state: BlogAgentState) -> dict:
        return await decide_images(state, llm)
    
    # Build reducer subgraph
    reducer_graph = StateGraph(BlogAgentState)
    reducer_graph.add_node("merge_content", merge_content)
    reducer_graph.add_node("decide_images", decide_images_with_llm)
    reducer_graph.add_node("generate_and_place_images", generate_and_place_images)
    
    reducer_graph.add_edge(START, "merge_content")
    reducer_graph.add_edge("merge_content", "decide_images")
    reducer_graph.add_edge("decide_images", "generate_and_place_images")
    reducer_graph.add_edge("generate_and_place_images", END)
    
    return reducer_graph.compile()


if __name__ == "__main__":
    import asyncio
    
    async def main():
        
        subgraph = create_reducer_subgraph(llm=None)
        print("Reducer subgraph created successfully!")
    
    asyncio.run(main())
