
import os
import sys
#TODO: Remove this when running as a module
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# pyrefly: ignore [missing-import]
from agents.blog_agent import BlogAgentState   
# pyrefly: ignore [missing-import]
from langgraph.graph import StateGraph, END,START
# from utils.agent_prompts import DECIDE_IMAGES_SYSTEM
from Model.agent_models import Plan
from typing import Dict, Any
# from google import genai
# from google.genai import types
# pyrefly: ignore [missing-import]
from Model.agent_models import GlobalImagePlan

#TODO: Remove this when running as a module


raw_plan=Plan(
    "blog_title": "Mia Khalifa: A Look into Her Career, Success, and Current Status", 
    "audience": "general audience", 
    "tone": "informative and objective", 
    "tasks":[
        {
            "id": 1, 
            "title": "Introduction to Mia Khalifa", 
            "goal": "Understand who Mia Khalifa is and her background", 
            "bullets":["Mia Khalifa's early life and career", 'Her rise to fame as an adult film star', 'Transition to other ventures'], 
            "target_words":200, 
            "section_type":'intro'
        },
        {
            "id": 2, 
            "title": "Career Highlights and Success", 
            "goal": "Learn about Mia Khalifa's notable achievements and success", 
            "bullets":['Her time in the adult film industry', 'Notable awards and recognition', 'Business ventures and investments'], 
            "target_words":300, 
            "section_type":'core'
        },
        {
            "id": 3, 
            "title": "Challenges and Controversies", 
            "goal": "Understand the challenges and controversies Mia Khalifa faced", 
            "bullets":['Criticism and backlash from the public', 'Health issues and wellness', 'Social media presence and impact'], 
            "target_words":250, 
            "section_type":'common_mistakes'
        },
        {
            "id": 4, 
            "title": "Current Status and Recent Updates", 
            "goal": "Get an update on Mia Khalifa's current life and projects", 
            "bullets":['Recent interviews and public appearances', 'Current business ventures and collaborations', 'Personal life and relationships'], 
            "target_words":220, 
            "section_type":'examples'
        },
        {
            "id": 5, 
            "title": "Conclusion and Legacy", 
            "goal": "Reflect on Mia Khalifa's legacy and impact", 
            "bullets":['Lasting impact on the adult film industry', 'Influence on social media and pop culture', 'Charity work and philanthropy'], 
            "target_words":200, 
            "section_type":'conclusion'
        }
        ]
)

# ============================================================
# 8) ReducerWithImages (subgraph)
#    merge_content -> decide_images -> generate_and_place_images
# ============================================================
async def merge_content(state: BlogAgentState) -> dict:

    # plan = state["plan"]
    plan=raw_plan

    ordered_sections = [md for _, md in sorted(state["sections"], key=lambda x: x[0])]
    body = "\n\n".join(ordered_sections).strip()
    merged_md = f"# {plan.blog_title}\n\n{body}\n"
    print("\n\n\n ================= MERGED MARKDOWN =================\n\n\n")
    print(merged_md)
    print("\n\n\n ================= MERGED MARKDOWN =================\n\n\n")
    return {"merged_md": merged_md}


# async def decide_images(state: BlogAgentState) -> dict:
#     planner = llm.with_structured_output(GlobalImagePlan)
#     merged_md = state["merged_md"]
#     plan = state["plan"]
#     assert plan is not None

#     image_plan = planner.invoke(
#         [
#             SystemMessage(content=DECIDE_IMAGES_SYSTEM),
#             HumanMessage(
#                 content=(
#                     f"Blog kind: {plan.blog_kind}\n"
#                     f"Topic: {state['topic']}\n\n"
#                     "Insert placeholders + propose image prompts.\n\n"
#                     f"{merged_md}"
#                 )
#             ),
#         ]
#     )

#     return {
#         "md_with_placeholders": image_plan.md_with_placeholders,
#         "image_specs": [img.model_dump() for img in image_plan.images],
#     }


# async def _gemini_generate_image_bytes(prompt: str) -> bytes:
#     """
#     Returns raw image bytes generated by Gemini.
#     Requires: pip install google-genai
#     Env var: GOOGLE_API_KEY
#     """
    

#     api_key = os.environ.get("GOOGLE_API_KEY")
#     if not api_key:
#         raise RuntimeError("GOOGLE_API_KEY is not set.")

#     client = genai.Client(api_key=api_key)

#     resp = client.models.generate_content(
#         model="gemini-2.5-flash-image",
#         contents=prompt,
#         config=types.GenerateContentConfig(
#             response_modalities=["IMAGE"],
#             safety_settings=[
#                 types.SafetySetting(
#                     category="HARM_CATEGORY_DANGEROUS_CONTENT",
#                     threshold="BLOCK_ONLY_HIGH",
#                 )
#             ],
#         ),
#     )

#     # Depending on SDK version, parts may hang off resp.candidates[0].content.parts
#     parts = getattr(resp, "parts", None)
#     if not parts and getattr(resp, "candidates", None):
#         try:
#             parts = resp.candidates[0].content.parts
#         except Exception:
#             parts = None

#     if not parts:
#         raise RuntimeError("No image content returned (safety/quota/SDK change).")

#     for part in parts:
#         inline = getattr(part, "inline_data", None)
#         if inline and getattr(inline, "data", None):
#             return inline.data

#     raise RuntimeError("No inline image bytes found in response.")


# async def generate_and_place_images(state: State) -> dict:

#     plan = state["plan"]
#     assert plan is not None

#     md = state.get("md_with_placeholders") or state["merged_md"]
#     image_specs = state.get("image_specs", []) or []

#     # If no images requested, just write merged markdown
#     if not image_specs:
#         filename = f"{plan.blog_title}.md"
#         Path(filename).write_text(md, encoding="utf-8")
#         return {"final": md}

#     images_dir = Path("images")
#     images_dir.mkdir(exist_ok=True)

#     for spec in image_specs:
#         placeholder = spec["placeholder"]
#         filename = spec["filename"]
#         out_path = images_dir / filename

#         # generate only if needed
#         if not out_path.exists():
#             try:
#                 img_bytes = _gemini_generate_image_bytes(spec["prompt"])
#                 out_path.write_bytes(img_bytes)
#             except Exception as e:
#                 # graceful fallback: keep doc usable
#                 prompt_block = (
#                     f"> **[IMAGE GENERATION FAILED]** {spec.get('caption','')}\n>\n"
#                     f"> **Alt:** {spec.get('alt','')}\n>\n"
#                     f"> **Prompt:** {spec.get('prompt','')}\n>\n"
#                     f"> **Error:** {e}\n"
#                 )
#                 md = md.replace(placeholder, prompt_block)
#                 continue

#         img_md = f"![{spec['alt']}](images/{filename})\n*{spec['caption']}*"
#         md = md.replace(placeholder, img_md)

#     filename = f"{plan.blog_title}.md"
#     Path(filename).write_text(md, encoding="utf-8")
#     return {"final": md}

async def main():

    # build reducer subgraph
    reducer_graph = StateGraph(BlogAgentState)
    reducer_graph.add_node("merge_content", merge_content)
    # reducer_graph.add_node("decide_images", decide_images)
    # reducer_graph.add_node("generate_and_place_images", generate_and_place_images)
    reducer_graph.add_edge(START, "merge_content")
    reducer_graph.add_edge("merge_content", END)

    # reducer_graph.add_edge("merge_content", "decide_images")
    # reducer_graph.add_edge("decide_images", "generate_and_place_images")
    # reducer_graph.add_edge("generate_and_place_images", END)
    reducer_subgraph = reducer_graph.compile()

    final=await reducer_subgraph.ainvoke(
        {
            "topic": "Mia Khalifa",
            "plan": raw_plan
        }
    )

    return final

if __name__ == "__main__":
    import asyncio
    
    asyncio.run(main())